
// Generated by the inits tool.  DO NOT EDIT!
package http
import (
	httpserver "github.com/lfxnxf/frame/logic/inits/http/server"
)


func initRoute(s httpserver.Server) {

	s.ANY("/ping", ping)



}

